invenio_trends_ui/__init__.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""UI for Invenio-Search."""

from __future__ import absolute_import, print_function

from .ext import InvenioTrendsUI
from .version import __version__

__all__ = ('__version__', 'InvenioTrendsUI')

invenio_trends_ui/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""UI for Invenio-Search."""

from __future__ import absolute_import, print_function

from flask import Blueprint, render_template

blueprint = Blueprint(
        'invenio_trends_ui',
        __name__,
        url_prefix='/trends',
        template_folder='templates',
        static_folder='static',
)


@blueprint.route("/")
def dashboard():
    """Search page ui."""
    return render_template('invenio_trends_ui/dashboard.html')


@blueprint.route("/search")
def search():
    """Search page ui."""
    return render_template('invenio_trends_ui/dashboard.html')

invenio_trends_ui/templates/invenio_trends_ui/base.html
{#
# This file is part of Invenio.
# Copyright (C) 2015, 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <script src="{{ url_for('static', filename='node_modules/almond/almond.js') }}"></script>
    {%- block css %}{%- endblock css %}
    {%- block javascript %}{%- endblock javascript %}
</head>
<body>
{%- block page_header %}
    {% include "invenio_trends_ui/base_header.html" %}
{%- endblock page_header %}
{%- block body_inner %}
    hi
    {%- block page_body %}
    {%- endblock page_body %}
    there
{%- endblock body_inner %}
</body>
</html>

invenio_trends_ui/templates/invenio_trends_ui/base_header.html
{#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}
{%- block search %}
<form class="navbar-form navbar-left" action="{{url_for('invenio_trends_ui.search')}}" role="search">
  <div class="form-group">
    <div class="input-group">
      <input type="text" class="form-control" name="q" placeholder="{{_('Search')}}">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div>
</form>
{%- endblock search %}

invenio_trends_ui/templates/invenio_trends_ui/dashboard.html
{#
# This file is part of Invenio.
# Copyright (C) 2015, 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}

{% extends config.TRENDS_UI_BASE_TEMPLATE %}

{% set body_css_classes = ['trends'] %}

{%- block css %}
    {{ super() }}
    {% assets "invenio_trends_ui_css" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{%- endblock css %}

{%- block javascript %}
    {{ super() }}
    {% assets "invenio_trends_ui_js" %}
        <script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{%- block page_body %}

    <div class="trends-logo"></div>

    <div id="invenio-trends">
        <invenio-trends>

            <trends-dashboard
                    template="{{ url_for('static', filename='js/invenio_trends_ui/templates/dashboard.html') }}"
                    trends-api="{{ config.TRENDS_UI_TREND_API }}">
            </trends-dashboard>

        </invenio-trends>
    </div>
{%- endblock page_body %}

invenio_trends_ui/templates/invenio_trends_ui/header.html
{#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}

{% extends config.SEARCH_UI_HEADER_TEMPLATE %}

{%- block navbar_search %}
<invenio-search-bar
 template="{{ url_for('static', filename='templates/invenio_trends_ui/searchbar.html') }}"
 placeholder="{{ search_input_placeholder|default(_('Search')) }}">
</invenio-search-bar>
{%- endblock navbar_search %}